ProjectSWP391/Controllers/BlogManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectSWP391.DAO;
using ProjectSWP391.Models;
using System.Data;
using System.Globalization;
using System.Reflection.Metadata;
using System.Text.RegularExpressions;

namespace ProjectSWP391.Controllers
{
    public class BlogManagementController : Controller
    {
        private readonly BlogManagementDAO dao = new BlogManagementDAO();
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Index(string? search, bool isSearch, bool isAscending = false, int page = 1)
        {

            if (!string.IsNullOrEmpty(search))
            {
                var regex = new Regex("\\s{2,}");
                search = regex.Replace(search.Trim(), " ");
            }
            var blogs = dao.GetBlogs(search, isSearch, isAscending);

            //Paging:
            const int pageSize = 10;
            page = page < 1 ? 1 : page;

            var totalItems = blogs.Count();
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var currentPageItems = blogs
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewData["key"] = search;
            ViewBag.TotalItems = totalItems;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;

            ViewBag.IsAscending = isAscending; // OrderBy Date for BlogView
            return View(currentPageItems);
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Detail(int id)
        {
            var blog = dao.GetBlogById(id);
            if (blog == null)
            {
                return NotFound();
            }

            var accounts = dao.GetAccounts();

            string email = "";
            string fullName = "";
            int? role = 1;
            foreach (var account in accounts)
            {
                if (account.AccountId == blog.AccountId)
                {
                    email = account.Email;
                    fullName = account.FullName;
                    role = account.Role ?? 1;
                }
            }
            ViewBag.Email = email;
            ViewBag.FullName = fullName;
            ViewBag.Role = role;
            return View(blog);
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Create()
        {
            var accounts = dao.GetAccounts();
            ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
            return View();
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Blog blog)
        {
            blog.Title = blog.Title?.Trim();
            blog.Content = blog.Content?.Trim();

            if (string.IsNullOrWhiteSpace(blog.Title) || blog.Title.Length < 5)
            {
                ModelState.AddModelError("Title", "Title must have at least 5 characters.");
            }
            if (string.IsNullOrWhiteSpace(blog.Content) || blog.Title.Length < 10)
            {
                ModelState.AddModelError("Title", "Title must have at least 5 characters.");
            }
            if (!ModelState.IsValid)
            {
                var accounts = dao.GetAccounts();
                ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                return View("Create");
            }
            Blog b = dao.GetBlogs("", false, false).FirstOrDefault(b => b.Title.Trim().Equals(blog.Title));

            if (b != null)
            {
                ModelState.AddModelError("Title", "Title is already exists!!");
                var accounts = dao.GetAccounts();
                ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                return View("Create");
            }

            /*            DateTime tempDate;
                        if (!DateTime.TryParseExact(blog.BlogDate?.ToString(), "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out tempDate))
                        {
                            ModelState.AddModelError("BlogDate", "Invalid date format!");
                            var accounts = dao.GetAccounts();
                            ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                            return View("Create");
                        }
                        else if (tempDate < new DateTime(2000, 12, 31) || tempDate > DateTime.Now)
                        {
                            ModelState.AddModelError("BlogDate", "Date must be between 31/12/2000 and today!");
                            var accounts = dao.GetAccounts();
                            ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                            return View("Create");
                        }*/
            blog.BlogDate = DateTime.Now;
            dao.AddBlog(blog);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Edit(int id)
        {
            var blog = dao.GetBlogById(id);
            if (blog == null)
            {
                return NotFound();
            }

            var accounts = dao.GetAccounts();
            ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
            return View(blog);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Edit(Blog blog)
        {
            blog.Title = blog.Title?.Trim();
            blog.Content = blog.Content?.Trim();

            if (string.IsNullOrWhiteSpace(blog.Title) || blog.Title.Length < 5)
            {
                ModelState.AddModelError("Title", "Title must have at least 5 characters.");
            }
            if (string.IsNullOrWhiteSpace(blog.Content) || blog.Title.Length < 10)
            {
                ModelState.AddModelError("Title", "Title must have at least 5 characters.");
            }

            if (!ModelState.IsValid)
            {
                var accounts = dao.GetAccounts();
                ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                return View("Edit");
            }


            var b = dao.GetBlogs("", false, false).FirstOrDefault(b => b.Title.Trim().Equals(blog.Title));
            if (b != null)
            {
                ModelState.AddModelError("Title", "Title is already exists!!");
                var accounts = dao.GetAccounts();
                ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                return View(blog);
            }



            /*            DateTime tempDate;
                        if (!DateTime.TryParseExact(blog.BlogDate?.ToString(), "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out tempDate))
                        {
                            ModelState.AddModelError("BlogDate", "Invalid date format!");
                            var accounts = dao.GetAccounts();
                            ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                            return View("Edit");
                        }
                        else if (tempDate < new DateTime(2000, 12, 31) || tempDate > DateTime.Now)
                        {
                            ModelState.AddModelError("BlogDate", "Date must be between 31/12/2000 and today!");
                            var accounts = dao.GetAccounts();
                            ViewBag.AccountId = new SelectList(accounts, "AccountId", "FullName");
                            return View("Edit");
                        }*/
            blog.BlogDate = DateTime.Now;
            dao.EditBlog(blog);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Delete(int id)
        {
            Console.WriteLine(id);
            var blog = dao.GetBlogById(id);
            dao.DeleteBlog(blog);
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjectSWP391/Views/BlogManagement/Create.cshtml
@model ProjectSWP391.Models.Blog
@{
    ViewData["Title"] = "DashBoard";
    Layout = "_AdminLayout";
}


<h1>Create</h1>

<h4>Blog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="BlogManagement" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" maxlength="50" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" maxlength="1000" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label">Author</label>
                <select asp-for="AccountId" class="form-control" asp-items="ViewBag.AccountId">
                    <option value="">-- Select Author --</option>
                </select>
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ProjectSWP391/Views/BlogManagement/Detail.cshtml
@model ProjectSWP391.Models.Blog

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BlogDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BlogDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.FullName
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BlogId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectSWP391/Views/BlogManagement/Edit.cshtml
@model ProjectSWP391.Models.Blog

@{
    ViewData["Title"] = "DashBoard";
    Layout = "_AdminLayout";
}

<h1>Edit</h1>

<h4>Blog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="BlogManagement" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BlogId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" maxlength="50" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" maxlength="1000" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <select asp-for="AccountId" class="form-control" asp-items="ViewBag.AccountId">
                    <option value="">-- Select Account --</option>
                </select>
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ProjectSWP391/Views/BlogManagement/Index.cshtml
@model List<ProjectSWP391.Models.Blog>
@{
    ViewData["Title"] = "DashBoard";
    Layout = "_AdminLayout";
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-dDr+X0F8ebV7SHmsZsGSjrH+Tfjld0Bn1XbHRwv9F7EoMjikFyGwZY3Qn7Sv7+yj" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        h1 {
            color: #333;
        }

        a {
            text-decoration: none;
            color: #007bff;
        }

        .search-bar {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }

            .search-bar input[type="text"] {
                padding: 10px;
                width: 300px;
                border-radius: 20px;
                border: none;
                outline: none;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
            }

                .search-bar input[type="text"]:focus {
                    border: 1px solid #000;
                }

        .table {
            width: 90%;
            margin: 0 auto;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        img {
            max-width: 120px;
            max-height: 120px;
        }

        .pagination-container {
            margin-top: 20px;
            text-align: center;
        }

        .pagination {
            display: inline-block;
            padding-left: 0;
            margin: 0;
            border-radius: 0.25rem;
        }

        .page-item {
            display: inline;
        }

            .page-item a {
                position: relative;
                float: left;
                padding: 0.5rem 0.75rem;
                margin-left: -1px;
                line-height: 1.25;
                color: #007bff;
                background-color: #fff;
                border: 1px solid #dee2e6;
            }

            .page-item.active a {
                z-index: 2;
                color: #fff;
                background-color: #007bff;
                border-color: #007bff;
            }
    </style>
</head>
<body>
    <h2 style="text-align:center">Blog Management</h2>
    <p>
        <a asp-action="CreateBlog" asp-controller="CustomerManagement" class="btn btn-outline-dark mt-auto width: 8vw;">Create</a>
    </p>
    <form asp-action="Index" method="get">
        <input type="hidden" name="isSearch" value="false" />
        <button type="submit" class="btn btn-dark edt-button-submit">Load</button>
    </form>

    <div class="search-bar">
        <form method="get" asp-action="Index" id="search-form">
            <input value="@ViewData["key"]" type="text" placeholder="Search by Service Name, Price" name="search" id="search-input" maxlength="20">
            <input type="hidden" name="isSearch" value="true" />
        </form>
    </div>


    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>
                    Date
                    @if (ViewBag.IsAscending)
                    {
                        <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage, search = ViewData["key"], isSearch = false, isAscending = false })"><i class="fas fa-chevron-up"></i></a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage, search = ViewData["key"], isSearch = false, isAscending = true })"><i class="fas fa-chevron-down"></i></a>
                    }

                </th>
                <th>Author</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.BlogId</td>
                    <td><a asp-action="Detail" asp-route-id="@item.BlogId">@item.Title</a></td>
                    <td style="max-width: 450px;">
                        @if (item.Content.Length >= 150)
                        {
                            @item.Content.Substring(0, 150)
                            <span>...</span>
                        }
                        else
                        {
                            @item.Content
                        }
                    </td>
                    <td>@item.BlogDate</td>
                    <td>@item.Account.FullName</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.BlogId"><i class="fas fa-edit"></i></a>|
                        <a href="#" type="button" onclick="ConfirmDeleteBlog(@item.BlogId)"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <!--Paging-->
    <div class="pagination-container">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                @if (ViewBag.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage - 1, search = ViewData["key"], isSearch = false })" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                }

                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                {
                    <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", new { page = i, search = ViewData["key"], isSearch = false })">@i</a>
                    </li>
                }

                @if (ViewBag.CurrentPage < ViewBag.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage + 1, search = ViewData["key"], isSearch = false })" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</body>
<script>
    document.getElementById('search-input').addEventListener('keydown', function (event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            document.getElementById('search-form').submit();
        }
    });

    function ConfirmDeleteBlog(id) {
        var res = confirm("Are you sure you want to delete this Blog?");
        if (res == true) {
            window.location.assign("/BlogManagement/Delete?id=" + id);
        } else {
            return false;
        }
    }
</script>