ProjectSWP391/Controllers/ServiceManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectSWP391.DAO;
using ProjectSWP391.Models;
using System.Data;
using System.Text.RegularExpressions;
using X.PagedList;

namespace ProjectSWP391.Controllers
{
    public class ServiceManagementController : Controller
    {
        private readonly ServiceManagementDAO ServiceDao = new ServiceManagementDAO();
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Index(string? search, bool isSearch, bool isAscendingPrice = false, int page = 1)
        {
            const int pageSize = 10;
            page = page < 1 ? 1 : page;

            if (!string.IsNullOrEmpty(search))
            {
                var regex = new Regex("\\s{2,}");
                search = regex.Replace(search.Trim(), " ");
            }
            var services = ServiceDao.GetServices(search, isSearch, isAscendingPrice);
            var totalItems = services.Count();
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var currentPageItems = services
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewData["key"] = search;
            ViewBag.TotalItems = totalItems;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;

            ViewBag.IsAscendingPrice = isAscendingPrice; // OrderBy Price for ServiceView
            return View(currentPageItems);
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Details(int id)
        {
            Service service = ServiceDao.GetServiceById(id);
            if (service == null)
            {
                return NotFound();
            }
            //Get category name
            using var context = new SWP391_V4Context();
            ServiceCategory? sg = context.ServiceCategories.Where(s => s.ScategoryId == service.ScategoryId).FirstOrDefault();
            if (sg != null)
            {
                ViewBag.ScategoryName = sg.ScategoryName;
                //Get Related Service in a category
                if (context.Services.Count() - 1 <= 4)
                {
                    List<Service> services = context.Services.Where(s => s.ServiceId != id && s.ScategoryId == sg.ScategoryId).ToList();
                    ViewBag.relateService = services;
                }
                else
                {
                    List<Service> services = context.Services.Where(s => s.ServiceId != id && s.ScategoryId == sg.ScategoryId).Take(4).ToList();
                    ViewBag.relateService = services;
                }
            }
            return View(service);
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Create()
        {
            var categories = ServiceDao.GetServiceCategories();
            ViewBag.ScategoryId = new SelectList(categories, "ScategoryId", "ScategoryName");
            return View();
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Service service)
        {
            service.ServiceName = service.ServiceName?.Trim();
            service.Description = service.Description?.Trim();
            service.Image = service.Image?.Trim();

            if (string.IsNullOrWhiteSpace(service.ServiceName) || service.ServiceName.Length < 5)
            {
                ModelState.AddModelError("ServiceName", "ServiceName must have at least 5 characters.");
            }

            if (service.Price <= 0)
            {
                ModelState.AddModelError("Price", "Price must be greater than 0.");
            }

            if (service.ScategoryId == null)
            {
                ModelState.AddModelError("ScategoryId", "Category must be choose");
            }

            if (!ModelState.IsValid)
            {
                var categories = ServiceDao.GetServiceCategories();
                ViewBag.ScategoryId = new SelectList(categories, "ScategoryId", "ScategoryName");
                return View("Create");
            }

            Service s = ServiceDao.GetServices("", false, false).FirstOrDefault(s => s.ServiceName.Trim().Equals(service.ServiceName));

            if (s != null)
            {
                ModelState.AddModelError("ServiceName", "ServiceName is already exists!!");
                var categories = ServiceDao.GetServiceCategories();
                ViewBag.ScategoryId = new SelectList(categories, "ScategoryId", "ScategoryName");
                return View("Create");
            }

            ServiceDao.AddService(service);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Edit(int id)
        {

            var service = ServiceDao.GetServiceById(id);
            if (service == null)
            {
                return NotFound();
            }
            var categories = ServiceDao.GetServiceCategories();
            ViewBag.ScategoryId = new SelectList(categories, "ScategoryId", "ScategoryName");
            return View(service);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Edit(Service service)
        {
            service.ServiceName = service.ServiceName?.Trim();
            service.Description = service.Description?.Trim();
            service.Image = service.Image?.Trim();

            if (string.IsNullOrWhiteSpace(service.ServiceName) || service.ServiceName.Length < 5)
            {
                ModelState.AddModelError("ServiceName", "ServiceName must have at least 5 characters.");
            }

            if (service.Price <= 0)
            {
                ModelState.AddModelError("Price", "Price must be greater than 0.");
            }

            if (service.ScategoryId == null)
            {
                ModelState.AddModelError("ScategoryId", "Category must be choose");
            }

            if (!ModelState.IsValid)
            {
                var categories = ServiceDao.GetServiceCategories();
                ViewBag.ScategoryId = new SelectList(categories, "ScategoryId", "ScategoryName");
                return View("Create");
            }

            Service s = ServiceDao.GetServices("", false, false).FirstOrDefault(s => s.ServiceName.Trim().Equals(service.ServiceName));

            if (s != null)
            {
                ModelState.AddModelError("ServiceName", "ServiceName is already exists!!");
                var categories = ServiceDao.GetServiceCategories();
                ViewBag.ScategoryId = new SelectList(categories, "ScategoryId", "ScategoryName");
                return View("Edit");
            }
            ServiceDao.EditService(service);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(AuthenticationSchemes = "Auth", Roles = "1")]
        public IActionResult Delete(int id)
        {
            Console.WriteLine(id);
            var service = ServiceDao.GetServiceById(id);
            ServiceDao.DeleteService(service);
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjectSWP391/Views/ServiceManagement/Create.cshtml
@model ProjectSWP391.Models.Service
@{
    ViewData["Title"] = "DashBoard";
    Layout = "_AdminLayout";
}

<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<h1>Create Service</h1>

<hr />
<div style="width: 70%">
    <form asp-action="Create" asp-controller="ServiceManagement" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label>Image:</label>
            <div style="width: 80px; height: 80px;">
                <img id="avatarContainer" style="width: 100%; height: 100%; border-radius: 50%; border: 1px solid black" />
            </div>
                <input type="file" style="margin-top: 10px;" accept="image/*" id="imageInput" />
        </div>
            <div class="form-group">
                <label asp-for="ServiceName" class="control-label"></label>
                <input asp-for="ServiceName" class="form-control" maxlength="30" />
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" maxlength="30" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" maxlength="6" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ScategoryId" class="control-label"></label>
                <select asp-for="ScategoryId" class="form-control" asp-items="ViewBag.ScategoryId">
                    <option value="">-- Select Category --</option>
                </select>
                <span asp-validation-for="ScategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</body>
<script>
    var fileToUpload = null;
    $('#imageInput').change(function () {
        fileToUpload = $(this)[0].files[0];
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#avatarContainer').prop('src', e.target.result);
        };

        if (fileToUpload) {
            reader.readAsDataURL(fileToUpload);
        }
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ProjectSWP391/Views/ServiceManagement/Details.cshtml
@using ProjectSWP391.Models.ServiceModel;
@model ProjectSWP391.Models.Service

@{
    ViewData["Title"] = "Service Details";
}
<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ServiceName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.Image" width="120px" height="120px" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Scategory)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.ScategoryName
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ServiceId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectSWP391/Views/ServiceManagement/Edit.cshtml
@model ProjectSWP391.Models.Service

@{
    ViewData["Title"] = "DashBoard";
    Layout = "_AdminLayout";
}

<h1>Edit</h1>

<h4>Service</h4>
<hr />
<div style="width: 70%">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ServiceId" />
        <div class="form-group">
            <label>Image:</label>
            <div style="width: 80px; height: 80px;">
                <img id="avatarContainer" style="width: 100%; height: 100%; border-radius: 50%; border: 1px solid black" />
            </div>
            <input type="file" style="margin-top: 10px;" accept="image/*" id="imageInput" />
        </div>
        <div class="form-group">
            <label asp-for="ServiceName" class="control-label"></label>
            <input asp-for="ServiceName" class="form-control" maxlength="30" />
            <span asp-validation-for="ServiceName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" maxlength="30" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="control-label"></label>
            <input asp-for="Price" class="form-control" maxlength="6" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
            </label>
        </div>
        <div class="form-group">
            <label asp-for="ScategoryId" class="control-label"></label>
            <select asp-for="ScategoryId" class="form-control" asp-items="ViewBag.ScategoryId">
                <option value="">-- Select Category --</option>
            </select>
            <span asp-validation-for="ScategoryId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Edit" class="btn btn-primary" />
        </div>
    </form>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ProjectSWP391/Views/ServiceManagement/Index.cshtml
@model List<ProjectSWP391.Models.Service>
@{
    ViewData["Title"] = "DashBoard";
    Layout = "_AdminLayout";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-dDr+X0F8ebV7SHmsZsGSjrH+Tfjld0Bn1XbHRwv9F7EoMjikFyGwZY3Qn7Sv7+yj" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        h1 {
            color: #333;
        }

        a {
            text-decoration: none;
            color: #007bff;
        }

        .search-bar {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }

            .search-bar input[type="text"] {
                padding: 10px;
                width: 300px;
                border-radius: 20px;
                border: none;
                outline: none;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
            }

                .search-bar input[type="text"]:focus {
                    border: 1px solid #000;
                }

        .table {
            width: 90%;
            margin: 0 auto;
        }

        th, td {
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        img {
            max-width: 120px;
            max-height: 120px;
        }

        .pagination-container {
            margin-top: 20px;
            text-align: center;
        }

        .pagination {
            display: inline-block;
            padding-left: 0;
            margin: 0;
            border-radius: 0.25rem;
        }

        .page-item {
            display: inline;
        }

            .page-item a {
                position: relative;
                float: left;
                padding: 0.5rem 0.75rem;
                margin-left: -1px;
                line-height: 1.25;
                color: #007bff;
                background-color: #fff;
                border: 1px solid #dee2e6;
            }

            .page-item.active a {
                z-index: 2;
                color: #fff;
                background-color: #007bff;
                border-color: #007bff;
            }
    </style>
</head>

<body>
    <h2 style="text-align:center">Service Management</h2>
    <p>
        <a asp-action="Create" class="btn btn-outline-dark mt-auto width: 8vw;">Create New</a>
    </p>
    <form asp-action="Index" method="get">
        <input type="hidden" name="isSearch" value="false" />
        <button type="submit" class="btn btn-dark edt-button-submit" >Load</button>
    </form>

    <div class="search-bar">
        <form method="get" asp-action="Index" id="search-form">
            <input value="@ViewData["key"]" type="text" placeholder="Search by Service Name, Price" name="search" id="search-input" maxlength="20">
            <input type="hidden" name="isSearch" value="true" />
        </form>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Image
                </th>
                <th>
                    Price
                    @if (ViewBag.IsAscendingPrice)
                    {
                        <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage, search = ViewData["key"], isSearch = false, isAscendingPrice = false })"><i class="fas fa-chevron-up"></i></a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", new { page = ViewBag.CurrentPage, search = ViewData["key"], isSearch = false, isAscendingPrice = true })"><i class="fas fa-chevron-down"></i></a>
                    }
                </th>
                <th>
                    Active
                </th>
                <th>
                    Category
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ServiceId)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ServiceId">@item.ServiceName</a>
                    </td>
                    <td style="max-width: 450px;">
                        @if (item.Description.Length >= 150)
                        {
                            @item.Description.Substring(0, 150)
                            <span>...</span>
                        }
                        else
                        {
                            @item.Description
                        }
                    </td>
                    <td>
                        <img src="@item.Image" width="120px" height="120" alt="Not found">
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Scategory.ScategoryName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ServiceId"><i class="fas fa-edit"></i></a> |
                        <a href="#" type="button" onclick="ConfirmDelete(@item.ServiceId)"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <!-- Paging -->
    <div class="pagination-container">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                @if (ViewBag.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage - 1, search = ViewData["key"], isSearch = false })" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                }

                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                {
                    <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", new { page = i, search = ViewData["key"], isSearch = false })">@i</a>
                    </li>
                }

                @if (ViewBag.CurrentPage < ViewBag.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage + 1, search = ViewData["key"], isSearch = false })" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</body>

<script>
    document.getElementById('search-input').addEventListener('keydown', function (event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            document.getElementById('search-form').submit();
        }
    });

    function ConfirmDelete(id) {
        var res = confirm("Are you sure you want to delete this Service?");
        if (res == true) {
            window.location.assign("/ServiceManagement/Delete?id=" + id);
        } else {
            return false;
        }
    }
</script>