ProjectSWP391/Models/ServiceList.cs
using System;
using System.Collections.Generic;

namespace ProjectSWP391.Models
{
    public partial class ServiceList
    {
        public int ServiceListId { get; set; }
        public int BookingId { get; set; }
        public int ServiceId { get; set; }

        public virtual Booking Booking { get; set; } = null!;
        public virtual Service Service { get; set; } = null!;
    }
}

ProjectSWP391/Controllers/CustomerManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSWP391.Models;
using ProjectSWP391.Models.ServiceModel;
using System.Diagnostics;
using System.Reflection;
using X.PagedList;

namespace ProjectSWP391.Controllers
{
    public class CustomerManagementController : Controller
    {
        private readonly string[] _PriceFilter = { "< 20$", "20$ - 50$", "51$ - 75$", "> 75$" };

        private readonly IWebHostEnvironment _webHostEnvironment;

        public CustomerManagementController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public Booking? GetCurrentBooking(int? cusID)
        {
            //Customer ID can not equal to 0
            if (cusID == 0) return null;
            Booking? bk = context.Bookings.Where(b => ((b.BookingDate.Date == DateTime.Today.Date && b.Shift > DateTime.Now.Hour)
            || (b.BookingDate.Date > DateTime.Today.Date)) && b.CustomerId == cusID).FirstOrDefault();

            if (bk != null)
            {
                return bk;
            }
            return null;
        }

        public IActionResult LandingPage(int? booked, string[]? message)
        {
            if(message != null)
            {
                ViewBag.message = message;
            }
            List<Product> products = context.Products.OrderByDescending(p => p.Quantity).Take(8).ToList();
            List<Service> services = context.Services.OrderBy(s => s.Price).Take(6).ToList();
            var blogs = context.Blogs.OrderByDescending(b => b.BlogDate).Take(4).Select(b => new
            {
                ID = b.BlogId,
                Title = b.Title,
                Content = b.Content,
                Date = b.BlogDate,
                Author = b.Account.FullName
            }).ToList();
            ViewBag.BlogList = blogs;
            ViewBag.ServiceList = services;

            //Check if user has book or not
            Account? acc = Global.CurrentUser;
            int? id = acc == null ? 0 : acc.AccountId;
            Booking? bk = GetCurrentBooking(id);
            if (bk != null)
            {
                ViewBag.currentBooking = bk;
            }
            else
            {
                //if guest enter booked phone number then show message
                if (booked != null)
                {
                    Booking? booking = context.Bookings.Where(b => b.BookingId == booked).FirstOrDefault();
                    if (booking != null)
                    {
                        ViewBag.currentBooking = booking;
                    }
                }
            }
            return View(products);
        }

        public IActionResult ProductList(int? page, string? sn, string? sc, int sp)
        {
            // Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            if (sn == null) sn = String.Empty;
            ViewBag.searchName = sn;
            if (sc == null) sc = String.Empty;
            //filter by name and category
            var products = (from product in context.Products
                            join pcategory in context.ProductCategories
                            on product.PcategoryId equals pcategory.PcategoryId
                            where product.ProductName.Contains(sn) && pcategory.PcategoryName.Contains(sc) && product.IsActive == true
                            select product).OrderBy(p => p.ProductId);
            //Get all service category
            var categories = context.ProductCategories.ToList();
            ViewBag.categoryFilter = categories;
            //Save the previous searchCategory
            ViewBag.searchCategory = sc;
            //Get Price filter list
            ViewBag.priceFilter = _PriceFilter;
            //Save the previuos searchPrice
            ViewBag.searchPrice = sp;
            // số service hiển thị trên 1 trang
            int pageSize = 8;

            int pageNumber = (page ?? 1);

            //filter by price
            switch (sp)
            {
                case 1:
                    {
                        var filterProducts = products.Where(s => s.Price < 20).OrderBy(p => p.Price).ToList();
                        return View("~/Views/CustomerManagement/ProductList.cshtml", filterProducts.ToPagedList(pageNumber, pageSize));
                    }
                case 2:
                    {
                        var filterProducts = products.Where(s => s.Price >= 20 && s.Price <= 50).OrderBy(p => p.Price).ToList();
                        return View("~/Views/CustomerManagement/ProductList.cshtml", filterProducts.ToPagedList(pageNumber, pageSize));
                    }
                case 3:
                    {
                        var filterProducts = products.Where(s => s.Price > 50 && s.Price <= 75).OrderBy(p => p.Price).ToList();
                        return View("~/Views/CustomerManagement/ProductList.cshtml", filterProducts.ToPagedList(pageNumber, pageSize));
                    }
                case 4:
                    {
                        var filterProducts = products.Where(s => s.Price > 75).OrderBy(p => p.Price).ToList();
                        return View("~/Views/CustomerManagement/ProductList.cshtml", filterProducts.ToPagedList(pageNumber, pageSize));
                    }
                default:
                    {
                        return View("~/Views/CustomerManagement/ProductList.cshtml", products.ToPagedList(pageNumber, pageSize));
                    }
            }
        }

        [HttpPost]
        public IActionResult FilterProduct()
        {
            string searchName = Request.Form["searchName"];
            string searchCategory = Request.Form["searchCategory"];
            int searchPrice = Convert.ToInt32(Request.Form["searchPrice"]);
            return ProductList(1, searchName, searchCategory, searchPrice);
        }

        public IActionResult ServiceList(int? page, string? sn, string? sc, int sp)
        {
            // Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            if (sn == null) sn = String.Empty;
            ViewBag.searchName = sn;
            if (sc == null) sc = String.Empty;
            //filter by name and category
            var services = (from service in context.Services
                            join scategory in context.ServiceCategories
                            on service.ScategoryId equals scategory.ScategoryId
                            where service.ServiceName.Contains(sn) && scategory.ScategoryName.Contains(sc) && service.IsActive == true
                            select service).OrderBy(s => s.ServiceId);
            //Get all service category
            var categories = context.ServiceCategories.ToList();
            ViewBag.categoryFilter = categories;
            //Save the previous searchCategory
            ViewBag.searchCategory = sc;
            //Get Price filter list
            ViewBag.priceFilter = _PriceFilter;
            //Save the previuos searchPrice
            ViewBag.searchPrice = sp;
            // số service hiển thị trên 1 trang
            int pageSize = 6;

            int pageNumber = (page ?? 1);

            //filter by price
            switch (sp)
            {
                case 1:
                    {
                        var filterServices = services.Where(s => s.Price < 20).OrderBy(s => s.Price).ToList();
                        return View("~/Views/CustomerManagement/ServiceList.cshtml", filterServices.ToPagedList(pageNumber, pageSize));
                    }
                case 2:
                    {
                        var filterServices = services.Where(s => s.Price >= 20 && s.Price <= 50).OrderBy(s => s.Price).ToList();
                        return View("~/Views/CustomerManagement/ServiceList.cshtml", filterServices.ToPagedList(pageNumber, pageSize));
                    }
                case 3:
                    {
                        var filterServices = services.Where(s => s.Price > 50 && s.Price <= 75).OrderBy(s => s.Price).ToList();
                        return View("~/Views/CustomerManagement/ServiceList.cshtml", filterServices.ToPagedList(pageNumber, pageSize));
                    }
                case 4:
                    {
                        var filterServices = services.Where(s => s.Price > 75).OrderBy(s => s.Price).ToList();
                        return View("~/Views/CustomerManagement/ServiceList.cshtml", filterServices.ToPagedList(pageNumber, pageSize));
                    }
                default:
                    {
                        return View("~/Views/CustomerManagement/ServiceList.cshtml", services.ToPagedList(pageNumber, pageSize));
                    }
            }
        }

        [HttpPost]
        public IActionResult FilterService()
        {
            string searchName = Request.Form["searchName"];
            string searchCategory = Request.Form["searchCategory"];
            int searchPrice = Convert.ToInt32(Request.Form["searchPrice"]);
            return ServiceList(1, searchName, searchCategory, searchPrice);
        }

        private readonly SWP391_V4Context context = new SWP391_V4Context();
        public IActionResult ServiceDetail(int? sId, int pageFeedback = 1)
        {
            Service? service = context.Services.Where(s => s.ServiceId == sId).FirstOrDefault();
            if (service == null)
            {
                return NotFound();
            }
            //Get category name
            ServiceCategory? sg = context.ServiceCategories.Where(s => s.ScategoryId == service.ScategoryId).FirstOrDefault();
            if (sg != null)
            {
                ViewBag.ScategoryName = sg.ScategoryName;

ProjectSWP391/Views/CustomerManagement/BlogDetail.cshtml
@using ProjectSWP391.Models;
@model Blog

@{
    if (Global.CurrentUser != null && (Global.CurrentUser.Role == 1 || Global.CurrentUser.Role == 2))
    {
        Layout = "_AdminLayout";
    }
}
<div class="container" style="padding: 50px 0 0 0">
    <div style="padding: 10px 10px 30px 10px; width: 32.20339%; float: left; margin-right: 1.69492%;">
        <div style="max-width: 180px; padding: 0 0 30px 0; border-bottom: 0.5px solid black;">
            <img src="/image/brand_logo.png" style="width: 60%; height: auto; border-radius: 50%; margin-bottom: 15px; background-color: black; border: 3px solid darkgoldenrod" />
            <h4>SB Blogs</h4>
            <p style="margin-bottom: 15px; font-size: 15px; color: dodgerblue; text-decoration: underline;">@@Sblogs</p>
            <p style="font-size: 15px; color: #b2c3cb;">Let our stories guide you</p>
        </div>
        <div style="padding: 30px 0 0 0; max-width: 180px;">
            <p style="font-size: 15px; color: #b2c3cb; margin-bottom: 15px; font-weight: bold;">Only on Smart Beauty</p>
            <p style="font-size: 15px; color: dodgerblue; text-decoration: underline;">#SmartBeauty</p>
        </div>
    </div>

    <div class="content-area" style="padding: 0 10px 80px 10px; width: 49.15254%; float: left; margin-right: 1.69492%; overflow-x: hidden;">
        <div style="padding: 0px 0 10px 0">
            <h1>@Model.Title</h1>
        </div>
        <div style="padding: 10px 0 30px 0; font-size: 15px; color: #b2c3cb">
            <p>By <span style="text-decoration: underline; color: dodgerblue;">@Model.Account.FullName</span></p>
            @*<p>@Model.BlogDate.ToString("dd/MM/yyyy");</p>*@
        </div>
        <div style="padding: 10px 0 10px 0; font-size: 15px;">
            @Html.Raw(Model.Content)
        </div>
    </div>
    <div style="width: 15.25424%; float: left; margin-right: 1.69492%;"></div>
</div>

<style>
    p, h1, h4 {
        margin-bottom: 0;
    }

    .content-area img {
        width: 100%;
        height: auto;
        object-fit: contain;
    }
</style>

ProjectSWP391/Views/CustomerManagement/CreateBlog.cshtml
@using ProjectSWP391.Models;
@using ProjectSWP391.Models.ServiceModel;
@model Blog

<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdn.tiny.cloud/1/xv3ddyptnibjrh8do09youtndlg1guo6fldl1x35prt87p6u/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <link href="/css/CreateBlog.css" rel="stylesheet" />
</head>


<body>
    @if (Global.CurrentUser == null)
    {
        <h5 class="text-danger text-center" style="margin-top: 40vh;">Please login to create a new blog <a href="/Authentication/Login">Login</a></h5>
    }
    else
    {
        if(Global.CurrentUser.Role == 2 || Global.CurrentUser.Role == 1)
        {
            Layout = "_AdminLayout";
        }
        <div style="width: 100%; padding: 20px 0 30px 0; background-color: floralwhite;">
            <h3 class="text-center fw-bold">Smart Beauty Blogs</h3>
        </div>
        <div style="width: 100%; padding: 0; background-color: #eeeeee;">
            <form id="myForm" asp-action="@(Model != null?"EditBlog":"CreateBlog")" asp-controller="CustomerManagement" method="post">
                <div style="width: 100%; display: flex; padding: 15px 25px 15px 25px; background-color: white;">
                    <div style="flex-grow: 19; margin-right: 20px;">
                        <label id="title_lb" style="font-size: 18px; font-weight: bold; transition: font-size 0.5s ease;">Blog Title</label><br />
                        @if (Model != null)
                        {
                            <input asp-for="Title" id="title_tb" type="text" value="@Model.Title" style="border: none; outline: none; border-bottom: 2px solid red; width: 100%; font-size: 16px;" name="title" title="Blog title contains 20 - 200 characters" required />
                            <input type="text" value="@Model.BlogId" asp-for="BlogId" style="display: none" />
                        }
                        else
                        {
                            <input asp-for="Title" id="title_tb" type="text" style="border: none; outline: none; border-bottom: 2px solid red; width: 100%; font-size: 16px;" name="title" title="Blog title contains 20 - 200 characters" required />
                        }
                    </div>
                    @if (Model != null)
                    {
                        <button id="submit_btn" type="submit" style="border: none; border-radius: 5px; height: 50px; color: white; background-color: lightgray; flex-grow: 1" disabled><i class="fa-solid fa-caret-right fa-lg"></i> Update</button>
                    }
                    else
                    {
                        <button id="submit_btn" type="submit" style="border: none; border-radius: 5px; height: 50px; color: white; background-color: lightgray; flex-grow: 1" disabled><i class="fa-solid fa-caret-right fa-lg"></i> Post</button>
                    }
                </div>
                <textarea asp-for="Content" id="myTextarea" name="content" style="border-radius: 5px; box-shadow: 0px 16px 46px -22px rgba(0,0,0,0.75)" required pattern="^.{100,}$" title="You must write at least 50 characters"></textarea>
            </form>
        </div>
        <script>
            var content = "";
            var form = document.getElementById("myForm");
            var text_area = document.getElementById("myTextarea");
            var button = document.getElementById("submit_btn");
            var title_tb = document.getElementById("title_tb");

            tinymce.init({
                selector: "textarea",
                height: 800,
                plugins: [
                    'advlist autolink lists link image charmap print preview anchor',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table paste code help wordcount'
                ],
                toolbar: 'undo redo | formatselect | ' +
                    'bold italic backcolor | link image media table mergetags | alignleft aligncenter ' +
                    'alignright alignjustify | bullist numlist outdent indent | ' + 'emoticons charmap | ' +
                    'removeformat | help',
                menubar: false,
                content_css: [
                    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i'
                ],
                init_instance_callback: function (editor) {
                    var content = editor.getContent();
                    var modifiedContent = modifyImgElements(content);
                    editor.setContent(modifiedContent);
                },
                setup: function (editor) {
                    editor.on('input', function () {
                        content = editor.getContent().replace(/<[^>]+>/g, '');
                        if ((title_tb.value.trim().length >= 20 && title_tb.trim().value.length <= 200) && content.trim().length >= 100) {
                            button.disabled = false;
                            button.style.backgroundColor = "orange";
                        }
                        else {
                            button.disabled = true;
                            button.style.backgroundColor = "lightgray";
                        }
                    });
                    editor.on('paste', function (e) {
                        var clipboardData = e.clipboardData || window.clipboardData;
                        content = clipboardData.getData('text/plain');
                        if ((title_tb.value.trim().length >= 20 && title_tb.trim().value.length <= 200) && content.trim().length >= 100) {
                            button.disabled = false;
                            button.style.backgroundColor = "orange";
                        }
                        else {
                            button.disabled = true;
                            button.style.backgroundColor = "lightgray";
                        }
                    });
                    editor.on('init', function () {
                        content = editor.getContent();
                    });
                },
                images_upload_url: '@Url.Action("UploadImage")',
                images_upload_handler: function (blobInfo, success, failure) {
                    // Custom logic to handle image upload

                    // Create a FormData object and append the file
                    var formData = new FormData();
                    formData.append('file', blobInfo.blob(), blobInfo.filename());

                    // Make an AJAX request to upload the image
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("UploadImage")',
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function (response) {
                            success(response.location); // Insert the image into the editor
                        },
                        error: function () {
                            failure('Image upload failed'); // Notify TinyMCE about the failure
                        }
                    });
                }
            });

            // Add an event listener to the button click
            button.addEventListener("click", function (event) {
                event.preventDefault();

                text_area.innerHTML = tinymce.get("myTextarea").getContent();

                form.submit();
            });

            document.getElementById("title_tb").onfocus = function () {
                document.getElementById("title_lb").style.fontSize = "15px";
            }
            document.getElementById("title_tb").onblur = function () {
                document.getElementById("title_lb").style.fontSize = "18px";
            }

            //Validate the content and title

            document.getElementById("title_tb").oninput = function () {
                if ((title_tb.value.trim().length >= 20 && title_tb.value.trim().length <= 200) && content.trim().length >= 100) {
                    button.disabled = false;
                    button.style.backgroundColor = "orange";
                }
                else {
                    button.disabled = true;
                    button.style.backgroundColor = "lightgray";
                }
            };

            function modifyImgElements(content) {
                var tempElement = document.createElement('div');
                tempElement.innerHTML = content;

                var imgElements = tempElement.getElementsByTagName('img');
                for (var i = 0; i < imgElements.length; i++) {
                    var imgElement = imgElements[i];
                    imgElement.style.width = "100%";
                    imgElement.style.height = "auto";
                }

                return tempElement.innerHTML;
            }
        </script>
    }
</body>
</html>
<style>
    body {
        background-color: #eeeeee;
        padding-top: 0;
        font-size: 18px;
    }

    .container-fluid {
        margin: 0;
        padding: 0;
    }

    #title_tb:invalid {
        border-bottom: 2px solid red;
    }

    #title_tb:valid {
        border-bottom: 2px solid green;
    }

    textarea img {
        width: 100%;
        height: auto;
        object-fit: contain;
    }
    #content-container{
        padding-left: 0;
        padding-right: 0;
    }
</style>